backend:
  name: git-gateway
  branch: master
  commit_messages:
    create: 'Create {{collection}} â€œ{{slug}}â€'
    update: 'Update {{collection}} â€œ{{slug}}â€'
    delete: 'Delete {{collection}} â€œ{{slug}}â€'
    uploadMedia: '[skip ci] Upload â€œ{{path}}â€'
    deleteMedia: '[skip ci] Delete â€œ{{path}}â€'

media_folder: static/img
public_folder: /img

locale: 'fr'

show_preview_links: true

slug:
  encoding: "ascii"
  clean_accents: true
  sanitize_replacement: "-"

logo_url: https://a.wattpad.com/useravatar/Perkytarsier.256.946301.jpg
collections:
  - name: blog
    label: "ActualitÃ©"
    folder: "src/pages/actualites"
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    required: false
    fields:
      - {label: "Template Key", name: templateKey, widget: hidden, default: "blog-post"}
      - {label: "Titre", name: title, widget: string}
      - {label: "Date de publication", name: date, widget: datetime}
      - {label: "Sur la page d'accueil", name: featuredpost, widget: boolean, default: true, required: false}
      - {label: "Introduction", name: description, widget: text, required: false}
      - {label: "Image principale", name: featuredimage, widget: image, required: false}
      - {label: "Texte principal", name: body, widget: markdown, required: false}
      - {label: "Tags", name: tags, widget: list, required: false}
      - name : document_list
        label : "Documents"
        widget: list
        label_singular: "Fichier"
        required: false
        fields:
          - {name: document_item, label: "Document", widget: file, required: true}
          - {name: document_title, label: "Nom du fichier", widget: string, required: false}

  - name: basicpage
    label: "Pages"
    folder: "src/pages/basicpage"
    # create: true
    slug: "{{slug}}"
    required: false
    fields:
      - {label: "Template Key", name: templateKey, widget: hidden, default: "basic-page"}
      - {label: "URL", name: forcedURL, widget: string}
      - {label: "URL Parent", name: parentUrl, widget: string}
      - {label: "Titre", name: title, widget: string}
      - {label: "Image principale", name: featuredimage, widget: image, required: false}
      - {label: "Introduction", name: description, widget: text, required: false}
      - {label: "Texte principal", name: body, widget: markdown, required: false}
      - name : document_list
        label : "Documents"
        widget: list
        label_singular: "Fichier"
        required: false
        fields:
          - {name: document_item, label: "Document", widget: file, required: true}
          - {name: document_title, label: "Nom du fichier", widget: string, required: false}
      - name: team_list
        label: "Ã‰quipe"
        label_singular: "Membre"
        widget: list
        required: false
        fields: 
          - {label: "Nom", name: team_name, widget: string, required: true}
          - {label: "Portrait", name: team_portrait, widget: "image", required: false}
          - {label: "Titre", name: team_title, widget: string, required: false}
          - {label: "Texte", name: team_text, widget: text, required: false}

  - name: "pages"
    label: "Pages"
    files:
      - file: "src/pages/index.md"
        label: "Landing Page"
        name: "index"
        fields:
          - {label: "Template Key", name: "templateKey", widget: "hidden", default: "index-page"}
          - {label: Title, name: title, widget: string}
          - {label: Image, name: image, widget: image}
          - {label: Heading, name: heading, widget: string}
          - {label: Subheading, name: subheading, widget: string}
          - {label: Mainpitch, name: mainpitch, widget: object, fields: [{label: Title, name: title, widget: string}, {label: Description, name: description, widget: text}]}
          - {label: Description, name: description, widget: string}
          - {label: Intro, name: intro, widget: object, fields: [{label: Heading, name: heading, widget: string}, {label: Description, name: description, widget: text}, {label: Blurbs, name: blurbs, widget: list, fields: [{label: Image, name: image, widget: image}, {label: Text, name: text, widget: text}]}]}
          - {label: Main, name: main, widget: object, fields: [{label: Heading, name: heading, widget: string}, {label: Description, name: description, widget: text}, {label: Image1, name: image1, widget: object, fields: [{label: Image, name: image, widget: image}, {label: Alt, name: alt, widget: string}]}, {label: Image2, name: image2, widget: object, fields: [{label: Image, name: image, widget: image}, {label: Alt, name: alt, widget: string}]}, {label: Image3, name: image3, widget: object, fields: [{label: Image, name: image, widget: image}, {label: Alt, name: alt, widget: string}]}]}
      - file: "src/pages/about/index.md"
        label: "About"
        name: "about"
        fields:
          - {label: "Template Key", name: "templateKey", widget: "hidden", default: "about-page"}
          - {label: "Title", name: "title", widget: "string"}
          - {label: "Body", name: "body", widget: "markdown"}
      - file: "src/pages/products/index.md"
        label: "Products Page"
        name: "products"
        fields:
          - {label: "Template Key", name: "templateKey", widget: "hidden", default: "product-page"}
          - {label: Title, name: title, widget: string}
          - {label: Image, name: image, widget: image}
          - {label: Heading, name: heading, widget: string}
          - {label: Description, name: description, widget: string}
          - {label: Intro, name: intro, widget: object, fields: [{label: Heading, name: heading, widget: string}, {label: Description, name: description, widget: text}, {label: Blurbs, name: blurbs, widget: list, fields: [{label: Image, name: image, widget: image}, {label: Text, name: text, widget: text}]}]}
          - {label: Main, name: main, widget: object, fields: [{label: Heading, name: heading, widget: string}, {label: Description, name: description, widget: text}, {label: Image1, name: image1, widget: object, fields: [{label: Image, name: image, widget: image}, {label: Alt, name: alt, widget: string}]}, {label: Image2, name: image2, widget: object, fields: [{label: Image, name: image, widget: image}, {label: Alt, name: alt, widget: string}]}, {label: Image3, name: image3, widget: object, fields: [{label: Image, name: image, widget: image}, {label: Alt, name: alt, widget: string}]}]}
          - {label: Testimonials, name: testimonials, widget: list, fields: [{label: Quote, name: quote, widget: string}, {label: Author, name: author, widget: string}]}
          - {label: Full_image, name: full_image, widget: image}
          - {label: Pricing, name: pricing, widget: object, fields: [{label: Heading, name: heading, widget: string}, {label: Description, name: description, widget: string}, {label: Plans, name: plans, widget: list, fields: [{label: Plan, name: plan, widget: string}, {label: Price, name: price, widget: string}, {label: Description, name: description, widget: string}, {label: Items, name: items, widget: list}]}]}

  - name: postproduction
    label: "Postproduction"
    folder: "src/pages/postproduction"
    create: true
    slug: "{{slug}}"
    required: false
    fields:
      - {label: "Template Key", name: templateKey, widget: hidden, default: "postproduction-post"}
      - {label: "Titre", name: title, widget: string}
      - {label: "Introduction", name: description, widget: text, required: false}
      - {label: "Image principale", name: featuredimage, widget: image, required: false}
      - {label: "Texte principal", name: body, widget: markdown, required: false}
      - name : document_list
        label : "ğŸ“ Documents"
        widget: list
        label_singular: "ğŸ“ƒ Fichier"
        required: false
        fields:
          - {name: document_item, label: "Document", widget: file, required: true}
          - {name: document_title, label: "Nom du fichier", widget: string, required: false}
      - name: team_list
        label: "ğŸ‘¥ Ã‰quipe"
        label_singular: "ğŸ‘¤ Membre"
        widget: list
        required: false
        fields: 
          - {label: "Nom", name: team_name, widget: string, required: true}
          - {label: "Portrait", name: team_portrait, widget: "image", required: false}
          - {label: "Titre", name: team_title, widget: string, required: false}
          - {label: "Texte", name: team_text, widget: text, required: false}

  - name: production
    label: "Productions"
    folder: "src/pages/production"
    create: true
    slug: "{{slug}}"
    required: false
    sortable_fields: ['commit_date', 'title', 'date']
    summary: "{{title}} [{{year}}]"
    preview_path: "production/{{slug}}"
    view_filters:
      - {label: 'Films avec VOD', field: vod, pattern: '.'}
    fields:
      - {label: "Template Key", name: templateKey, widget: hidden, default: "production-post", required: false}
      - {label: "ğŸ–‹ Titre", name: title, widget: string}
      - {label: "ğŸ“… Date de sortie", name: date, widget: datetime, hint: "Date rÃ©elle ou estimÃ©e. Seule l'annÃ©e est affichÃ©e, mais l'ensemble de la date sert au trie.", required: false}
      - {label: "ğŸ§‘â€ğŸ¨ RÃ©alisateurÂ·trice", name: director, widget: string, required: false}
      - {label: "ğŸ–¼ï¸ Image principale", name: featuredimage, widget: image, required: false}
      - {label: "ğŸ Bande-annonce", name: trailer, widget: string, hint: "URL de la vidÃ©o. Exemple : https://www.youtube.com/watch?v=9D0eyl7-XQA", required: false}
      - {label: "ğŸ“½ VOD", name: vod, widget: string, hint: "URL de la page de VOD.", required: false}
      - name: VOD_list,
        label: "ğŸ“½ VOD"
        label_singular: "lien VOD"
        widget: list
        required: false
        fields: 
          - {label: "ğŸ“½ Lien VOD", name: vod_item, widget: string, hint: "URL de la page de VOD.", required: false}
      - {label: "ğŸ’¬ Introduction", name: description, widget: markdown, buttons: ["bold", "italic", "link"], editorComponents: [], required: false}
  #     # - {label: "Sur la page d'accueil", name: featuredpost, widget: boolean, required: false}
  #     # - {label: "Tags", name: tags, widget: list, hint: "'documentaire' ou 'fiction'", required: false}
      - name: gallery_list
        label: "ğŸ–¼ï¸ Galerie"
        label_singular: "ğŸ–¼ï¸ Image"
        widget: list
        required: false
        fields: 
          - {label: "Image", name: gallery_img, widget: image, required: false}
          - {label: "LÃ©gende", name: gallery_caption, widget: text, required: false}
      - {label: "Texte principal", name: body, widget: markdown, required: false}
      - name : document_list
        label : "ğŸ“ Documents"
        widget: list
        label_singular: "ğŸ“ƒ Fichier"
        required: false
        fields:
          - {name: document_item, label: "Document", widget: file, required: true}
          - {name: document_title, label: "Nom du fichier", widget: string, required: false}
      - {label: "âš™ï¸ Fiche technique", name: technical, widget: markdown, required: false}
      - {label: "ğŸ§‘ğŸ¾â€ğŸ¤â€ğŸ§‘ğŸ¼ CrÃ©dits", name: credit, widget: markdown, required: false}
      - {label: "ğŸ† SÃ©lections", name: selection, widget: markdown, required: false}
      - {label: "ğŸ¦ Producteurs", name: productor, widget: markdown, required: false}

  - name: settings
    label: "RÃ©glages"
    files:
      - label: "Contact"
        name: contact
        file: src/settings/contact.json
        fields: 
          - {name: "address", label: "Adresse", widget: text, required: false}
          - {name: "phone", label: "TÃ©lÃ©phone", widget: string, required: false}
          - {name: "email", label: "Courriel", widget: string, required: false}
          - {name: "facebook", label: "Facebook", widget: string, required: false}
          - {name: "vimeo", label: "Vimeo", widget: string, required: false}